import "../globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { notFound } from "next/navigation"

import Navbar from "@/app/components/Navbar"
import Footer from "@/app/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang={"eng"}>
			<body className={inter.className}>
				<Navbar />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
