import "../globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { i18n } from "../../../i18n-config"

import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }))
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode
	params: { lang: string }
}) {
	return (
		<html lang={params.lang}>
			<body className={inter.className}>
				<Navbar />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
