import "./globals.css"
import type { Metadata } from "next"
import { ReactNode } from "react"
import ReduxProvider from "./context/ReduxProvider"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

type Props = {
	children: ReactNode
}

export default function RootLayout({ children }: Props) {
	return <ReduxProvider>{children}</ReduxProvider>
}
